defaults:
  - _self_
  - env: walker2d

seeds: 
- 0
- 1
- 2
# - 42
# - 3407 # https://arxiv.org/abs/2109.08203

tag: null
vec_envs: 1

train:
  lr: 1e-4
  weight_decay: 1e-3
  vec_envs: ${vec_envs}
  env_name: ${env.env_name}
  #train_steps: 455_000
  train_steps: 1000
  finetune_steps: 0
  #train_steps: 365_000
  #finetune_steps: 90_000
  batch_size: 256
  plot_interval: 500
  eval_interval: 500
  eval_episodes: 10
  warmup_steps: 10_000
  rtg_target: ${env.rtg_target}
  eval_drop_ps: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

buffer:
  _target_: buffer.SequenceBuffer
  env_name: ${env.env_name}
  dataset: medium
  sample_type: traj_length
  context_len: ${model.context_len}
  gamma: 1.0
  drop_cfg:
    drop_fn: const
    drop_p: 0.0
    finetune_drop_p: 0.8
    update_interval: 100
    drop_aware: ${model.drop_aware}
  
model:
  _target_: model.DecisionTransformer
  n_heads: 4
  n_blocks: 4
  drop_p: 0.1
  hidden_dim: 512
  context_len: 20
  reward_scale: 1000
  max_timestep: ${env.max_timestep}
  drop_aware: true

hydra:
  job:
    chdir: true
  run:
    dir: ./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}

lora:
  use_lora: true
  r: 8
  lora_alpha: 16
  lora_dropout: 0.0
  lora_save_path: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/lora
  lora_load_path: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/lora/
load_model:
  use_load_model: true
  #last ni .pt ha iranai!
  load_model_path: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d_medium_00
  # CUDA_VISIBLE_DEVICES=1 python main.py 

part_dropping:
  use_part_dropping: true
  drop_features: [0, 1, 2]

dynamic_lora:
  use_dynamic_lora: false
  lora_load_path:
    drop0_0: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/00
    drop0_1: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/01
    drop0_2: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/02
    drop0_3: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/03
    drop0_4: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/04
    drop0_5: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/05
    drop0_6: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/06
    drop0_7: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/07
    drop0_8: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/08
    drop0_9: /home/daikiyotsufuji/CODE/DeFog/mujoco/model/walker2d/09